version: 2
jobs:
  build:
    docker:
    - image: circleci/buildpack-deps:bullseye
    environment:
    - IMAGE_NAME: vpanian/do-circle-test-app:latest
    working_directory: /tmp/app
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build Docker image
        command: |
          echo "date: here suppose i build docker image with $CIRCLE_SHA1 "
          #"docker build  $IMAGE_NAME:$CIRCLE_SHA1 ."
          #"docker build /Users/vladpanian/ITOP-10310/circle/circle-test  -t vpanian/do-circle-test-app"
    - run:
        name: Push Docker Image
        command: |
          echo "date: here suppose i push docker image with $CIRCLE_SHA1 "
          #echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          #docker tag $IMAGE_NAME:latest $IMAGE_NAME:$CIRCLE_SHA1
          #docker push $IMAGE_NAME:$CIRCLE_SHA1
  deploy:
    docker:
    - image: circleci/buildpack-deps:bullseye
    working_directory: /tmp/app
    steps:
    - checkout
    - run:
        name: Install envsubst
        command: |
          sudo apt-get update && sudo apt-get -y install gettext-base
    - run:
        name: Deploy Code
        command: ./scripts/ci-deploy.sh
workflows:
  version: 2
  build-deploy-master:
    jobs:
    - build:
        filters:
          branches:
            only: master
    - deploy:
        filters:
          branches:
            only: master
        requires:
        - build
