version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bullseye
    environment:
      IMAGE_NAME: vpanian/do-circle-test-app:latest
    working_directory: /tmp/app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build  $IMAGE_NAME .
            echo "in docker build"
      - run:
          name: Push Docker Image
          command: 
            docker push $IMAGE_NAME
            echo "in docker push"
  deploy:
    docker:
      - image: circleci/buildpack-deps:bullseye
    working_directory: /tmp/app
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh
workflows:
  version: 2
  build-deploy-master:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
