on: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/base:2023.03'
    environment:
      IMAGE_NAME: vpanian/do-circle-test-app
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: pushdockerimage
          command: |
            docker push vpanian/do-circle-test-app
            echo "what an idiot stup"
  test:
    docker:
      - image: 'vpanian/do-circle-test-app:latest'
    steps:
      - checkout
      - run: echo "this is the test job"
  deploy:
    docker:
      - image: 'vpanian/do-circle-test-app:lates'
    steps:
      - checkout
      - run:
          name: Install envsubst
          command: |
            sudo apt-get update && sudo apt-get -y install gettext-base
      - run:
          name: Deploy Code
          command: ./scripts/ci-deploy.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
      - deploy

